# Site Settings
title:               Le Biochimiste
tagline:             Nouvelles scientifiques
description:
destination:        #/var/www/html/lebiochimiste.com/public_html/
baseurl:            #"/"
url:                #"https://www.lebiochimiste.com"
lang:               fr_CA

github:
  url:              #"https://www.github.com/normcyr/lebiochimiste.com"
author:
  name:              "Normand Cyr"
  email:             "normand.cyr@gmail.com"
  twitter:           "lebiochimiste"
  facebook:          "normand.cyr"
  github:            "normcyr"
  linkedin:          "normcyr"
  researchgate:      "Normand_Cyr"
navigation:
- title: À propos
  url: /apropos
- title: Articles
  url: /articles
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
